package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "simple_external_priority_queue",
  srcs = ["simple_external_priority_queue.cc"],
  deps = ["//bayes/branch_and_bound/external_priority_queue:simple_external_priority_queue"],
)
