package(default_visibility = ["//visibility:public"])

cc_library(
  name =  "greedy_local_search",
  hdrs = ["greedy_local_search.h"],
  srcs = ["greedy_local_search.cc"],
  deps = ["//bayes/branch_and_bound:graph"],
)
