package(default_visibility = ["//visibility:public"])
  
cc_binary(
  name = "bitset",
  srcs = ["bitset.cc"],
  deps = ["//bayes/branch_and_bound:bitset"],
)
 
cc_binary(
  name = "external_queue",
  srcs = ["external_queue.cc"],
  deps = ["//bayes/branch_and_bound:external_queue"],
)
 
cc_binary(
  name = "inverted_index",
  srcs = ["inverted_index.cc"],
  deps = ["//bayes/branch_and_bound:inverted_index"],
)

cc_binary(
  name = "instance",
  srcs = ["instance.cc"],
  deps = ["//bayes/branch_and_bound:instance"],
)

cc_binary(
  name = "indexed_variable",
  srcs = ["indexed_variable.cc"],
  deps = ["//bayes/branch_and_bound:indexed_variable"],
)

cc_binary(
  name = "variable",
  srcs = ["variable.cc"],
  deps = ["//bayes/branch_and_bound:variable"],
)

cc_binary(
  name = "graph",
  srcs = ["graph.cc"],
  deps = ["//bayes/branch_and_bound:graph"],
)

cc_binary(
  name = "branch_and_bound",
  srcs = ["branch_and_bound.cc"],
  deps = ["//bayes/branch_and_bound:branch_and_bound"],
)
