package(default_visibility = ["//visibility:public"])

cc_library(
  name = "grasp",
  hdrs = ["grasp.h"],
  srcs = ["grasp.cc"],
  deps = ["//bayes/branch_and_bound:graph",
          "//bayes/branch_and_bound:variable",
          "//bayes/branch_and_bound:inverted_index"],
)
