package(default_visibility = ["//visibility:public"])

cc_binary(
  name =  "ranker",
  srcs = ["ranker.cc"],
  deps = ["//bayes/branch_and_bound/inference:ranker"],
)

cc_binary(
  name =  "sampler",
  srcs = ["sampler.cc"],
  deps = ["//bayes/branch_and_bound/inference:sampler"],
)
